# Generated by Django 5.1 on 2025-08-04 20:30

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Property name or identifier", max_length=200
                    ),
                ),
                ("address", models.TextField(help_text="Full property address")),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("residential", "Residential"),
                            ("commercial", "Commercial"),
                            ("mixed", "Mixed Use"),
                            ("land", "Land"),
                        ],
                        default="residential",
                        max_length=20,
                    ),
                ),
                (
                    "acquisition_date",
                    models.DateField(help_text="Date property was acquired"),
                ),
                (
                    "purchase_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Purchase price of the property",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "current_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Current estimated value",
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about the property"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Properties",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("income", "Income"), ("expense", "Expense")],
                        max_length=10,
                    ),
                ),
                (
                    "category",
                    models.CharField(help_text="Schedule E category", max_length=50),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Transaction amount",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("date", models.DateField(help_text="Date of transaction")),
                (
                    "description",
                    models.CharField(
                        help_text="Brief description of transaction", max_length=200
                    ),
                ),
                (
                    "vendor",
                    models.CharField(
                        blank=True, help_text="Vendor or payee name", max_length=100
                    ),
                ),
                (
                    "receipt_reference",
                    models.CharField(
                        blank=True,
                        help_text="Receipt number or reference",
                        max_length=100,
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Additional notes")),
                (
                    "is_recurring",
                    models.BooleanField(
                        default=False, help_text="Is this a recurring transaction?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "property",
                    models.ForeignKey(
                        help_text="Property this transaction is associated with",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="ledger.property",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
